### ISSUE TITLE
Don't throw in case of not having enough permissions to access to root's home

### ISSUE THREAD

**Issue by badrAZ** [JsCommunity/app-conf#15]
On running a node script as a root which use `app-conf` and which change the current node process user to a non-root user, `App-conf` will throw an error because it will not have permissions to access to the root's home. For more details see https://github.com/vatesfr/xen-orchestra/issues/4854

**Comment by julien-f** [comment]
This issue is too specific, I will not ignore `EACCES` errors when the program is ran as `root`, drops privileges and is then unable to read its home directory.

We could ignore all `EACCES` errors when looking for configuration files but I don't think it's a good idea to do so silently as it is probably a misconfiguration which may lead to surprising behaviors.

**Comment by badrAZ** [comment]
Right, IMHO, a simple warning when `app-conf` don't have enough permissions to access to a directory and an error when `app-conf` don't find any configuration will be good.

**Comment by julien-f** [comment]
How can a library express a warning?

**Comment by badrAZ** [comment]
By using the node console.

**Comment by julien-f** [comment]
IMHO, libraries should never write to the console, and your solution of passing an additional param, while possible, is at best a work-around for a weird situation.

I'm closing this for now, feel free to ping me again if this is really necessary.
